# Generated by Django 5.2.7 on 2025-11-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options_remove_library_books_library_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book',
            new_name='books',
        ),
    ]
